spring:
  datasource:
    username: school_user
    password: root
    url: jdbc:postgresql://localhost:5432/school_db
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080
